spring:
  application.name: eBookRepository
  profiles:
    active: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/e_book_repository
    driver-class-name: org.postgresql.Driver
    name: e_book_repository
    username: postgres
    password: rootroot
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB



server:
  port: 8080
  servlet.context-path: /api

logging.level.org.hibernate.SQL: DEBUG
#hibernate.temp.use_jdbc_metadata_defaults: false
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false


custom:
  elastic:
    hostname: localhost
    port: 9200
    protocol: http
  storage:
    # with slash at the end
    location: ./storage/